// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lohynscmgxajnksmeiio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvaHluc2NtZ3hham5rc21laWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDQ3NDYsImV4cCI6MjA2MDgyMDc0Nn0.rm1subCdDBjI76uJylF1RQKAFEb6t46hmX2VGmqupf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);